version: "{build}"

# This will build all PRs targetting matching branches.
# Without this, each PR builds twice -- once for the PR branch HEAD,
# and once for the merge commit that github creates for each mergable PR.
branches:
  only:
    - master
    - still

# Disable normal Windows builds in favor of our test script.
build: off

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - bundler --version
  - bundle install
  - cinst ansicon

test_script:
  - bundle exec rake test --trace

environment:
  matrix:
    - ruby_version: '22'
    - ruby_version: '23'
    - ruby_version: '24'
    - ruby_version: '25'
    - ruby_version: '26'

